Adding common schedules
datacarpentry/genomics-workshop pull request #139
Opened 2023-05-26 16:01 UTC by sstevens2

Fixes #138

Noticed the heading levels when I went to edit this.  I left it as is to not make multiple changes in one PR but I think these should be level 2 headings.  My understanding is that there should only be one level 1 heading and then the other page headings should be hierarchical under it.

[Heading Accessibility Reference](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/)

2023-05-26 16:01 UTC, sstevens2 commented
I did make the subheadings in this section level 3 so they won't need to be edited if we switch the section headings to 2.

2023-05-26 16:02 UTC, sstevens2 commented on index.md
> +### Schedule A(2 days OR 4 half days)
```suggestion
### Schedule A (2 days OR 4 half days)
```

2023-05-26 16:33 UTC, JCSzamosi requested changes
It's a small thing, but can you make the spacing around the ampersand consistent? Right now you have "Half-day 3 &4:" twice, and then "Half-day 5&6:"

My preference would be for spaces before and after all ampersands, but I don't know if it matters once rendered.

2023-05-31 18:57 UTC, JCSzamosi commented
@twrightsman, I noticed you added this PR to the Workbench Transition milestone, but I don't think that's correct. Can you explain why you did that?

2023-05-31 19:46 UTC, sstevens2 commented on index.md
> +Half-day 3 &4 : [Data wrangling and processing](https://datacarpentry.github.io/wrangling-genomics/)
```suggestion
Half-day 3 & 4 : [Data wrangling and processing](https://datacarpentry.github.io/wrangling-genomics/)
```

2023-05-31 19:46 UTC, sstevens2 commented on index.md
> +Half-day 3 &4 : [Data wrangling and processing](https://datacarpentry.github.io/wrangling-genomics/)
```suggestion
Half-day 3 & 4 : [Data wrangling and processing](https://datacarpentry.github.io/wrangling-genomics/)
```

2023-05-31 19:46 UTC, sstevens2 commented on index.md
> +Half-day 5&6: [Intro to R and RStudio for Genomics](https://datacarpentry.org/genomics-r-intro/)
```suggestion
Half-day 5 & 6: [Intro to R and RStudio for Genomics](https://datacarpentry.org/genomics-r-intro/)
```

2023-05-31 19:48 UTC, sstevens2 commented
Nice catch @JCSzamosi!  I put in a commit with your change to spaces before and after as I agree that probably looks better.

> It's a small thing, but can you make the spacing around the ampersand consistent? Right now you have "Half-day 3 &4:" twice, and then "Half-day 5&6:"
> 
> My preference would be for spaces before and after all ampersands, but I don't know if it matters once rendered.
> 
> EDIT: I just realized I probably should have tagged @sstevens2 in this request.

2023-05-31 19:48 UTC, sstevens2 commented on index.md
> +Half-day 3 &4: [Intro to R and RStudio for Genomics](https://datacarpentry.org/genomics-r-intro/)
```suggestion
Half-day 3 & 4: [Intro to R and RStudio for Genomics](https://datacarpentry.org/genomics-r-intro/)
```

2023-05-31 19:49 UTC, twrightsman commented
> @twrightsman, I noticed you added this PR to the Workbench Transition milestone, but I don't think that's correct. Can you explain why you did that?

Sure thing. Any fork of the repository that was created before the Workbench transition will be invalid after the repository is transitioned to Workbench around September. So all PRs need to be resolved before the pre-transition milestone is due (September). It would probably be better named as "Workbench Transition Preparation"?

2023-05-31 20:21 UTC, JCSzamosi commented
> > @twrightsman, I noticed you added this PR to the Workbench Transition milestone, but I don't think that's correct. Can you explain why you did that?
> 
> Sure thing. Any fork of the repository that was created before the Workbench transition will be invalid after the repository is transitioned to Workbench around September. So all PRs need to be resolved before the pre-transition milestone is due (September). It would probably be better named as "Workbench Transition Preparation"?

Ohhh. I was confused. The genomics-organization repo has already transitioned to workbench, but now I see this one has not. I understand now.

2023-05-31 20:21 UTC, JCSzamosi approved these changes

2023-05-31 20:22 UTC, JCSzamosi commented
> Nice catch @JCSzamosi! I put in a commit with your change to spaces before and after as I agree that probably looks better.
> 

This looks good to me! I'm going to merge the pull request now.

2023-05-31 20:23 UTC, merged